name: quarto-workshop-slides
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - numpy
  - scikit-learn
  - pandas
  - pip
  - pip:
      - quarto-cli
